### ISSUE TITLE
Наш ответ ИД-картам

### ISSUE THREAD

**Issue by netwiz0rd** [yura-pepsicola/PepsiBay13#17]
Так как ключ-карт не будет, было бы удобнее запилить всплывающие сообщения при экзамайне по типу "О, это же [ИМЯ ФАМИЛИЯ]! Это наш(а) [РОЛЬ]!"

**Comment by Shararashik** [comment]
Я думаю можно оставить ID карты. Всё же доступ, как и на орбите, в некоторые супер-важные места будет ограничен.

**Comment by netwiz0rd** [comment]
ну пусть тогда они будут лежать все в шкафу на мостике
